name: cozy_data_example
environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cozy_data:
    path: ../
  dart_mappable: ^4.3.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
