name: cozy_data
description: A Swift-inspired persistent data management solution for Flutter. Provides simple, powerful, and type-safe way to persist your app's models with automatic UI updates.
version: 0.0.1-dev.1
homepage: https://github.com/yourusername/cozy_data

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  isar: 4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.10 # Flutter binaries for the Isar Database. because the Database is baed on isar and isar is not direct supported for flutter without theses binaries.
  path_provider: ^2.1.4
  source_gen: ^1.4.0
  build: ^2.3.1

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
