name: cozy_data
description: A Swift-inspired persistent data management solution for Flutter. Provides simple, powerful, and type-safe way to persist your app's models with automatic UI updates.
version: 1.0.0
repository: https://github.com/fodedoumbouya/cozy_data
issue_tracker: https://github.com/fodedoumbouya/cozy_data/issues

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  sqflite: ^2.3.3+1
  dart_mappable: ^4.3.0
  uuid: ^4.5.1
  path_provider: ^2.1.5
  sqlite3: ^2.4.7
  logger: ^2.5.0
  synchronized: ^3.1.0+1

dev_dependencies:
  flutter_lints: ^3.0.0
